services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.5.0
    container_name: imagix-dynamodb-local
    ports:
      - "4512:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
