services:
  dynamodb-test:
    image: amazon/dynamodb-local:2.5.0
    container_name: imagix-dynamodb-test
    ports:
      - "4512:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  dynamodb-dev:
    image: amazon/dynamodb-local:2.5.0
    container_name: imagix-dynamodb-dev
    user: root
    ports:
      - "4513:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./.dynamodb-data:/data
